name: caminhos_do_saber
description: Aplicativo para criação de material didatico para o ensino fundamental

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  printing: ^3.3.0
  pdf: ^1.6.0
  video_player: ^0.10.8+1
  camera: ^0.5.7+4
  built_value: ^7.0.9
  built_collection: ^4.3.2
  flutter_bloc: ^3.2.0
  bloc: ^3.0.0
  path_provider:
  path:
  meta: ^1.1.8
  equatable: ^1.1.1
  font_awesome_flutter: ^8.8.1
  cached_network_image: ^2.0.0


dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.3.0
  mockito: ^4.1.1
  bloc_test: ^3.0.0
  build_runner: ^1.8.0
  built_value_generator: ^7.0.9
  effective_dart: ^1.2.1
  test_coverage: ^0.4.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
